Import('env')


env = env.Clone()
env.Append(
    LIBS=['boost_unit_test_framework'],
    CPPDEFINES=['BOOST_TEST_DYN_LINK'],
)

# Add platform-specific MPI handling
mpi_libs = []
if env['PLATFORM'] == 'darwin':
    # On macOS, try openmpi or mpich from Homebrew
    mpi_libs = ['mpi']
elif env['PLATFORM'] == 'posix':
    mpi_libs = ['mpi']

tests = [
    env.Program('test_interpolate.cpp'),
    env.Program('test_younglaplace.cpp', LIBS=env['LIBS']+['sundials_core', 'sundials_arkode', 'sundials_nvecserial'] + mpi_libs),
]

Return('tests')
